[project]
name = "comfyui-model-manager"
description = "Lightweight native ComfyUI extension to browse, manage, scan, download, and upload models with SOCKS5 proxy and FFmpeg WebP support."
version = "3.1.0"
license = { file = "LICENSE" }
dependencies = [
    "markdownify",
    "pyyaml",
    "pillow",
    "requests",
    "pysocks",
]

[project.urls]
Repository = "https://github.com/wogam/ComfyUI-Model-Manager"

[tool.comfy]
PublisherId = "wogam"
DisplayName = "ComfyUI-Model-Manager"
Icon = ""

[tool.black]
line-length = 160
